'use client'
import { MyContextProvider } from './context/Context'
import './globals.sass'
import { Inter } from 'next/font/google'
import Search from './components/Search/page'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <MyContextProvider>
        <body className={inter.className}>
          <Search />
          {children}
        </body>
      </MyContextProvider>
    </html>
  )
}

